In [2]:
#Q1 a
import numpy as np
arr = np.array([1,2,3,6,4,5])
newArray = np.flipud(arr)
print(newArray)

[5 4 6 3 2 1]


In [3]:
#Q1 b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array2 = array1.flatten('C')
print(array2)

array3 = array1.flatten('F')
print(array3)

array4 = array1.reshape(-1)
print(array4)

[1 2 3 2 4 5 1 2 3]
[1 2 1 2 4 2 3 5 3]
[1 2 3 2 4 5 1 2 3]


In [4]:
#Q1 c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(f"Array 1 = {arr1}")
print(f"Array 2 = {arr2}")

print("arr1 > arr2")
print(np.greater(arr1,arr2))

print("arr1 >= arr2")
print(np.greater_equal(arr1,arr2))

print("arr1 < arr2")
print(np.less(arr1,arr2))

print("arr1 <= arr2")
print(np.less_equal(arr1,arr2))

print("arr1 = arr2")
print(np.equal(arr1,arr2))

if (np.array_equal(arr1,arr2)):
    print("arr1 == arr2")

else:
    print("They are not equal")

Array 1 = [[1 2]
 [3 4]]
Array 2 = [[1 2]
 [3 4]]
arr1 > arr2
[[False False]
 [False False]]
arr1 >= arr2
[[ True  True]
 [ True  True]]
arr1 < arr2
[[False False]
 [False False]]
arr1 <= arr2
[[ True  True]
 [ True  True]]
arr1 = arr2
[[ True  True]
 [ True  True]]
arr1 == arr2


In [5]:
#Q1 d
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Most frequently occuring element is = ", np.bincount(x).argmax());

y = np.array([1,1,1,2,3,4,2,4,3,3])
print("Most frequently occuring element is = ", np.bincount(y).argmax());

Most frequently occuring element is =  1
Most frequently occuring element is =  1


In [6]:
#Q1 e
gfg = np.matrix('[4,1,9; 12,3,1; 4,5,6]')

print("Sum of all elements of matrix = ", gfg.sum())
print("Sum of all Elements Row-wise = ", gfg.sum(axis=1))
print("Sum of all Elements Columns-wise = ", gfg.sum(axis=0))

Sum of all elements of matrix =  45
Sum of all Elements Row-wise =  [[14]
 [16]
 [15]]
Sum of all Elements Columns-wise =  [[20  9 16]]


In [7]:
#Q1 f
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Sum of diagonal elements of the Matrix = ", np.trace(n_array))

a, b = np.linalg.eig(n_array)
print("Eigen Values of the Matrix are = ", a)
print("Eigen Vectors of the Matrix are = ", b)
print("Inverse of Matrix = ", np.linalg.inv(n_array))
print("Determinant of matrix = ", np.linalg.det(n_array))

Sum of diagonal elements of the Matrix =  176
Eigen Values of the Matrix are =  [98.16835147 28.097044   49.73460452]
Eigen Vectors of the Matrix are =  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of Matrix =  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix =  137180.0000000001


In [8]:
#Q1 f
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Sum of diagonal elements of the Matrix = ", np.trace(n_array))

a, b = np.linalg.eig(n_array)
print("Eigen Values of the Matrix are = ", a)
print("Eigen Vectors of the Matrix are = ", b)
print("Inverse of Matrix = ", np.linalg.inv(n_array))
print("Determinant of matrix = ", np.linalg.det(n_array))

Sum of diagonal elements of the Matrix =  176
Eigen Values of the Matrix are =  [98.16835147 28.097044   49.73460452]
Eigen Vectors of the Matrix are =  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of Matrix =  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix =  137180.0000000001


In [9]:
#Q1 g
p = [[1,2],[2,3]]
q = [[4,5],[6,7]]
print("Product of the two matrices = ", np.matmul(p,q))
print("Covariance between the two matrices = ", np.cov(p,q))

p1 = [[1,2],[2,3],[4,5]]
q1 = [[4,5,1],[6,7,2]]
print("Product of the two matrices = ", np.matmul(p1,q1))
print("Covariance between the two matrices = ", np.cov(p1,q1))

Product of the two matrices =  [[16 19]
 [26 31]]
Covariance between the two matrices =  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
Product of the two matrices =  [[16 19  5]
 [26 31  8]
 [46 55 14]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [10]:
#Q1 h
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
print("Inner Product = ", np.inner(x,y))
print("Outer Product = ", np.outer(x,y))
print("Cartesian Product = ", np.cross(x,y))

Inner Product =  [[17 52]
 [13 62]]
Outer Product =  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product =  [[-20   4   7]
 [-84  36  20]]


In [11]:
#Q2 a
array1 = np.array([[1,-2,3],[-4,5,-6]])

print("Element wise absolute value = ", np.absolute(array1))

np.ndarray.flatten(array1)

print("25th percentile along every row : ", np.percentile(array1, 25, axis=1))
print("25th percentile along every column : ", np.percentile(array1, 25, axis=0))


print("50th percentile along every row : ", np.percentile(array1, 50, axis=1))
print("50th percentile along every column : ", np.percentile(array1, 50, axis=0))


print("75th percentile along every row : ", np.percentile(array1, 75, axis=1))
print("75th percentile along every column : ", np.percentile(array1, 75, axis=0))

print("Mean of each Column : ", np.mean(array1,axis=0))
print("Mean of each Row : ", np.mean(array1,axis=0))

print("Median of each Column : ", np.median(array1,axis=0))
print("Median of each Row : ", np.median(array1,axis=0))

print("Standard Deviation of each Column : ", np.std(array1,axis=0))
print("Standard Deviation of each Row : ", np.std(array1,axis=0))

Element wise absolute value =  [[1 2 3]
 [4 5 6]]
25th percentile along every row :  [-0.5 -5. ]
25th percentile along every column :  [-2.75 -0.25 -3.75]
50th percentile along every row :  [ 1. -4.]
50th percentile along every column :  [-1.5  1.5 -1.5]
75th percentile along every row :  [2.  0.5]
75th percentile along every column :  [-0.25  3.25  0.75]
Mean of each Column :  [-1.5  1.5 -1.5]
Mean of each Row :  [-1.5  1.5 -1.5]
Median of each Column :  [-1.5  1.5 -1.5]
Median of each Row :  [-1.5  1.5 -1.5]
Standard Deviation of each Column :  [2.5 3.5 4.5]
Standard Deviation of each Row :  [2.5 3.5 4.5]


In [12]:
#Q2 b
a = np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
print ("Floor : ", np.floor(a))
print ("Ceiling : ", np.ceil(a))
print ("Truncated Values : ", np.trunc(a))
print ("Rounded Values : ", np.round(a))

Floor :  [-2. -2. -1.  0.  1.  1.  3.]
Ceiling :  [-1. -1. -0.  1.  2.  2.  3.]
Truncated Values :  [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values :  [-2. -2. -0.  0.  2.  2.  3.]


In [13]:
#Q3 a
a = np.array([10,52,62,16,16,54,453])
print ("Sorted array : ", np.sort(a))
print ("Indices of sorted array : ", np.argsort(a))

a = np.sort(a)
print ("4 smallest elements : ", a[:4])
print ("5 largest elements : ", a[-5:])

Sorted array :  [ 10  16  16  52  54  62 453]
Indices of sorted array :  [0 3 4 1 5 2 6]
4 smallest elements :  [10 16 16 52]
5 largest elements :  [ 16  52  54  62 453]


In [13]:
from unicodedata import decimal

a = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
result1 = a[a != a.astype('float64')]
print ("Integer Elements only : ", result1)
print ("Float Elements only : ", a[a != a.astype(int)])

NameError: name 'np' is not defined

In [14]:
from PIL import Image
from pytesseract import image_to_string 
print(image_to_string(Image.open('/home/ABCD/Downloads/imageABC.png'),lang='eng'))

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3261716540.py, line 3)

In [2]:
# USING GRAY SCALE
from keras.preprocessing.image import save_img
from keras.preprocessing.image import img_to_array
img = load_img('dog.jpg', grayscale=True)
img_array = img_to_array(img)
save_img('dog_grayscale.jpg', img_array)
img = load_img('dog_grayscale.jpg')
print(type(img))
print(img.format)
print(img.mode)
print(img.size)
img.show()

ModuleNotFoundError: No module named 'tensorflow'